name: docs

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: "Version label (e.g., v0.1.0)"
        required: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-docs.txt

      - name: Build docs
        run: mkdocs build

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Deploy with mike
        env:
          VERSION: ${{ github.event.inputs.version || 'latest' }}
        run: |
          CURRENT_VERSION=${VERSION}
          if [ "$CURRENT_VERSION" = "latest" ]; then
            mike deploy --push --update-aliases latest
            mike set-default --push latest
          else
            mike deploy --push --update-aliases "$CURRENT_VERSION" latest
            mike set-default --push latest
          fi
